version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    depends_on: [prometheus]


  ###############################################################
  #                       My HelloWorld App                     #
  ###############################################################
  
    image: hello-world
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 512M


